describegpt: add --user-agent in help message
jqnatividad/qsv pull request #1095
Opened 2023-07-03 15:48 UTC by rzmk

## 🗺 Overview

Resolves #1082. Adds the `--user-agent` option to `describegpt`.

2023-07-03 15:48 UTC, rzmk commented
I'm curious how to verify this works properly.

2023-07-04 03:05 UTC, jqnatividad commented on src/cmd/describegpt.rs
> +    // If --user-agent is not specified, use an empty string as the default value
Hi @rzmk , you don't need to do this. Just set user_agent when setting up the reqwest client...

2023-07-04 03:08 UTC, jqnatividad commented on src/cmd/describegpt.rs
> +        .user_agent(user_agent.clone())
Just set user_agent right here, replacing this line with:

```rust
.user_agent(util::set_user_agent(args.flag_user_agent)?)
```

2023-07-04 03:10 UTC, jqnatividad requested changes
Hi @rzmk , just a few tweaks - see how its done by the `fetch` command for a quick reference

2023-07-04 03:19 UTC, jqnatividad commented on src/cmd/describegpt.rs
> +
Hi @rzmk , you don't need to do user_agent var. Just set user_agent directly when setting up the reqwest client below...

2023-07-04 03:20 UTC, jqnatividad requested changes
Made requested change on unneeded user_agent var clearer...

2023-07-04 04:12 UTC, rzmk commented
`args.flag_user_agent` wasn't in scope of the function `get_completion`, same with `args.max_token`. I've passed `args` now and removed the `user_agent` variable.

2023-07-04 11:33 UTC, merged