Draft: Implement new command `diff`
jqnatividad/qsv pull request #711
Opened 2023-01-04 22:42 UTC by janriemer

:warning: This is a draft PR. The following items need to be resolved first, before this PR can be merged:
- [ ] add tests
- [ ] document the new `diff` command in the docs
- [ ] wait for the next release of `csv-diff` - this PR currently depends on the top of the following branch in `csv-diff`:
https://gitlab.com/janriemer/csv-diff/-/tree/additions-for-qsv

Nevertheless, we open this PR, even though it is not finished, so that we can get early feedback on the implementation.

Closes #547

## Note to maintainers regarding kind of merge to be performed
I'd like this PR to __not__ be squash-merged, as I've spent a significant amount of time splitting the commits into atomic chunks. Thank you for considering this. :heart: 

## What this PR implements

This implements the new command `diff` for diffing two CSVs.
Usage is as follows:

```
Usage:
    qsv diff [options] [\<input-left\>] [\<input-right\>]
    qsv diff --help

Common options:

    -h, --help                  Display this message
    -o, --output <file>         Write output to <file> instead of stdout.
    --no-headers-left           When set, the first row will be considered as part of
                                the left CSV to diff. (When not set, the
                                first row is the header row and will be skipped during
                                the diff. It will always appear in the output.)
    --no-headers-right          When set, the first row will be considered as part of
                                the right CSV to diff. (When not set, the
                                first row is the header row and will be skipped during
                                the diff. It will always appear in the output.)
    --delimiter-left <arg>      The field delimiter for reading CSV data on the left.
                                Must be a single character. (default: ,)
    --delimiter-right <arg>     The field delimiter for reading CSV data on the right.
                                Must be a single character. (default: ,)
    --primary-key-idx <arg...>  The column indices that uniquely identify a record
                                as a comma separated list of indices, e.g. 0,1,2.
                                (default: 0)
```

## Examples

Diff csv_left.csv with csv_right.csv with default options and write the result to stdout:

`qsv diff path/to/csv_left.csv path/to/csv_right.csv`

Diff csv_left.csv with csv_right.csv and treat the first and third columns as unique keys for identifying a record. The result is written to the new file diffresult.csv:

`qsv diff --primary-key-idx 0,2 -o path/to/diffresult.csv path/to/csv_left.csv path/to/csv_right.csv`

The output of the diff command can look like the following:
```
diffresult,GlobalRank,TldRank,Domain,TLD,RefSubNets,RefIPs,IDN_Domain,IDN_TLD,PrevGlobalRank,PrevTldRank,PrevRefSubNets,PrevRefIPs
-,4,4,twitter.com,com,436953,2075089,twitter.com,com,4,4,436735,2077023
+,4,4,joinmastodon.org,org,436953,2075089,joinmastodon.org,org,4,4,436735,2077023
-,18,14,maps.google.com,com,203146,708101,maps.google.com,com,18,14,203197,708631
-,1,1,google.com,com,492918,2427561,google.com,com,1,1,492881,2429667
-,23,17,docs.google.com,com,184531,539376,docs.google.com,com,23,17,184740,540129
+,19,1,goo.gl,gl,200037,649215,goo.gl,gl,19,1,200069,649539
-,20,15,plus.google.com,com,198766,712276,plus.google.com,com,20,15,198784,713207
-,15,11,play.google.com,com,216317,611475,play.google.com,com,15,11,216267,612046
```
The diff result can be seen in the first column:
- "-" means that the record was deleted in the file on the right (can be seen after the first two records in the example output)
- "+" means that the record was added in the file on the right
- consecutive "-", "+", where the key columns are equal means the record was modified in some columns that were not key columns (this can be seen in the first two rows of the example output)

The following is an svg recording of a terminal, in which this new command `diff` is executed and `time`d on the majestic million csv with some artificial changes introduced. The CSVs have 1,000,000 rows x 12 columns:
https://gist.githubusercontent.com/janriemer/0e86a236a7174af6faed1b981815a5ea/raw/2ab235a2bdd5798f2348d42da48fdda276fb5f0f/qsv_diff_recording.svg

## New dependency `csv-diff`

The actual operation of diffing two CSVs is provided by the external crate `csv-diff`, so this uses this new dependency:
https://crates.io/crates/csv-diff (see also 90a7035, where this dependency is introduced)

`csv-diff` uses a default feature where a rayon thread pool is used. As `qsv` doesn't use a global thread pool, this feature might be unnecessarily activated in `csv-diff`. In future iterations this default feature should be considered to be disabled, but for now we leave it as is to make things simple.

Please keep in mind that `csv-diff` is in an early stage of development, so the new `diff` command should be considered __experimental__ for now.

## :warning: Current limitations

### If both CSVs have headers, they __must not__ be in a different ordering
=> see also these issues in `csv-diff`:
    - https://gitlab.com/janriemer/csv-diff/-/issues/6
    - https://gitlab.com/janriemer/csv-diff/-/issues/3

Currently, there is __no error happening__ in `qsv`, when the above scenario occurs, so the __diffresult will be wrong__. Until the issue is not resolved in `csv-diff`, it _should_ be fairly easy to check this in `qsv` itself and raise an error, if this is happening.

### Currently does not support any kind of indexing
Some other commands in `qsv` support indexing, which the new `diff` command does not support. This is due to how the diff is implemented in the underlying crate `csv-diff`.
It will probably be __very difficult__ to integrate an index into `csv-diff`, because it's architecture doesn't allow it. Having said that, the new `diff` command is __very fast__ (~800ms for the majestic million csv dataset with 1,000,000 rows x 12 columns - see above).

With that, it is probably the fastest csv differ in the world! :rocket: 

## Future work/enhancements

Besides the work that is needed for resolving some of the current limitations, there are other possibilities for improvement:
- Regarding the new column _diffresult_ that shows the result of the diff
  - provide an option to specify a different header name, as this might collide with an already existing column that has this header name
  - provide an option to specify whether the column _diffresult_ should be the first or last column in the result of the diff
- for modified rows
  - provide an option for marking the values that are actually different
Example (note the [-value-] and [+value+]):
```
diffresult,GlobalRank,TldRank,Domain,TLD,RefSubNets,RefIPs,IDN_Domain,IDN_TLD,PrevGlobalRank,PrevTldRank,PrevRefSubNets,PrevRefIPs
-,4,4,[-twitter.com-],[-com-],436953,2075089,[-twitter.com-],[-com-],4,4,436735,2077023
+,4,4,[+joinmastodon.org+],[+org+],436953,2075089,[+joinmastodon.org+],[+org+],4,4,436735,2077023
```

2023-01-05 02:41 UTC, jqnatividad requested changes
Beyond running `cargo +nightly fmt`, I think an "early merge" is OK as per my comment above ☝️ .

2023-01-06 19:29 UTC, jqnatividad commented
Hi @janriemer , unless you say otherwise, I'll go ahead with an "early" merge tomorrow, OK?

2023-01-06 23:04 UTC, janriemer commented
Hey @jqnatividad,
first of all, thank you for all your swift responses and the quick review! :heart: 

> unless you say otherwise, I'll go ahead with an "early" merge tomorrow, OK?

After checking your timezone, this means I have ~20 hours left from now on until the merge. This is fine with me! :laughing: :+1:   
Until then, I'd like to
- [ ] fix rustfmt issue (thank you for the hint regarding `cargo +nightly fmt`)
- [ ] get a proper release out for `csv-diff` on crates.io, so we don't depend on a pure branch

I'll provide an update here, when this is done.

Now adressing your other points above:

> logging is not just for debugging, we also use it in production ourselves for monitoring/benchmarking, so feel free to use it in `diff`.

Thank you for the suggestion, I haven't thought about that. :+1: I'll create a follow-up issue for it here. Also, `csv-diff` should have logging as well (currently has none).

> I think `diff` is a good candidate for a --json option as well.

Good point! I'll create a follow-up issue for it here. Might later also be integrated into `csv-diff` itself, but not sure yet.

> I've taken the "[release early, release often](https://en.wikipedia.org/wiki/Release_early,_release_often)" philosophy to heart. qsv's users are quite savvy and sophisticated CLI veterans, and they can get to exercise the command better with real-life use cases/data, and give valuable feedback/suggestions that can even seed diff's test cases.

:smile: Yes, I like this attitude and you are totally right! :hugs: To be clear here: a merge without tests in `diff` is fine with me. Also, `csv-diff` itself has a pretty good testsuite already (> 50 tests). What we will need to test here in `qsv` are the "integration points", so e.g.:
- writing out the diff in general (not _necessarily_ whether diff is correct => this is already handled by tests in `csv-diff`)
- writing out the headers
  - when there is no diff vs. when there is a diff
  - when one csv has headers and the other not
- __not__ writing out the headers
  - when both csv's have no headers
- etc.

> Witness how the recently added `to` command was merged without tests, and already, it's being [exercised by some qsv power users. It even triggered a security advisory on a to dependency that was flagged by the GitHub Actions bot after the "early" merge](https://github.com/jqnatividad/qsv/issues?q=is%3Aissue+is%3Aopen+kindly).

This is wild! :rocket: 

> FYI, not taking advantage of docs.rs at this stage is a conscious decision [...]

Oh, I see. I'll update the corresponding task in this PR as resolved then.

> cargo +nightly fmt ensures that even casual users can make some sense of the source code after reading the usage text.

Ohhhh, that's why you are using nightly features and the alignment formatting on structs. Makes much more sense now. Thanks for clarifying.

Regarding your comment in the corresponding issue (#547) of this PR: I've seen it and will respond to it tomorrow (already pretty late in the night for me).

Thank you for the good and "uncomplicated" collaboration on this. I really appreciate it! :heart:

2023-01-07 15:47 UTC, janriemer commented
Good news @jqnatividad :tada: 

I've updated this PR with the following changes and marked the corresponding tasks as resolved:
- apply nightly rustfmt
- depend on a version of `csv-diff` that is on crates.io

### :warning: Before you merge this, one important note, I haven't mentioned yet
For the equality comparison `csv-diff` currently relies on the hashing algorithm [xxhash with 128 bits](https://docs.rs/xxhash-rust/latest/xxhash_rust/xxh3/fn.xxh3_128.html). This is __not a cryptographically secure hash__. However,[according to collision tests on the official xxhash repo](https://github.com/Cyan4973/xxHash/wiki/Collision-ratio-comparison#testing-128-bit-hashes-), there are __no known collisions__ for this high number of bits, so it is ok for equality checks where security is not important.

__Conclusion__: the new `diff` command (as of now) should not be used in adversarial environments, where an attacker could manipulate the csv data.

I plan to implement an alternative hash function, which is crypto-secure: [BLAKE3](https://docs.rs/blake3/latest/blake3/). Which hash function to use in `csv-diff` will eventually be configurable via Cargo features, but until then please consider the above warning.

Thank you. :slightly_smiling_face: 

### Future change: rename --primary-key-idx => --key-idx
Another thing that has catched my eye: the current option `--primary-key-idx` in our new `diff` command is pretty "chatty". I think a more succinct variant would be to use `--key-idx`. This would be in alignment with [the Python package `csv-diff`](https://pypi.org/project/csv-diff/).

I hope we can change this in future versions of `qsv` without causing to much churn. :crossed_fingers: 

Until then - happy merging and releasing :rocket: I'm super excited for `diff` to land in `qsv`! :tada:

2023-01-07 16:22 UTC, jqnatividad commented
Great! And no worries on the non-crypto secure hash - qsv `sample` and `sort` are both using non-crypto secure RNGs, as for those use-cases, we're randomizing sampling/sorting and I just added DevSkim lint ignores to suppress warnings.

But that's good you called out the non-crypto secure hash `diff` is using.  I'll also add replacing those RNGs with a crypto secure ones in the backlog.

And yep - changing the API in the future is not an issue, especially, given "**_OUR_**" :wink: project's release tempo.

2023-01-07 16:22 UTC, merged

2023-01-27 16:04 UTC, dufferzafar commented
Wuhoo! We finally have diff! 🥳  

The both of you can thank me anytime for creating the original issue & bringing y'all together! 😛